name: systemd, alsa, pipewire, ao, dummy, jack, pipe, stdout,using a build folder.

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Install Dependencies
      run: sudo apt-get -y --no-install-recommends install libpipewire-0.3-dev libplist-utils xmltoman libpopt-dev libconfig-dev libasound2-dev libao-dev libjack-dev libglib2.0-dev libmosquitto-dev avahi-daemon libavahi-client-dev libssl-dev libsoxr-dev libplist-dev libsodium-dev libavutil-dev libavcodec-dev libavformat-dev libgcrypt-dev
    - name: Configure
      run: |
        mkdir build
        cd build
        autoreconf -i ..
        ../configure --sysconfdir=/etc --with-alsa --with-pipewire --with-ao --with-dummy --with-jack --with-pipe --with-stdout --with-soxr --with-avahi --with-ssl=openssl --with-systemd-startup --with-dbus-interface --with-mpris-interface --with-mqtt-client --with-airplay-2
    - name: Make
      run: |
        cd build
        make -j
    - name: Install
      run: |
        cd build
        sudo make install
    - name: Invoke
      run: |
        sudo systemctl start shairport-sync
    - name: Terminate
      run: |
        sudo systemctl stop shairport-sync

