# Builds and pushes a docker image in the following scenarios:
# When a commit is made to 'master' or 'development'.
# Tag pattern
# 'master'      - rolling, rolling-classic
# 'development' - development, development-classic
# When a tag is created.
# Tag pattern: '[tag]' & '[tag]-classic', plus 'latest' & 'classic'
name: Build and conditionally push docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  docker-vars:
    uses: ./.github/workflows/docker-vars.yaml
  build-docker-image-and-publish:
    name: Build and conditionally push docker image
    needs:
      - docker-vars
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: classic
            dockerfile: ./docker/classic/Dockerfile
            build_args: |
              SHAIRPORT_SYNC_BRANCH=.
          - name: main
            dockerfile: ./docker/Dockerfile
            build_args: |
              SHAIRPORT_SYNC_BRANCH=.
              NQPTP_BRANCH=${{ needs.docker-vars.outputs.nqptp_branch }}
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        if: needs.docker-vars.outputs.push_docker_image == 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Checkout shairport sync repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6.18.0
        env:
          registry_and_name: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}
        with:
          context: ./
          file: ${{ matrix.dockerfile }}
          platforms: ${{ needs.docker-vars.outputs.docker_platforms }}
          push: ${{ needs.docker-vars.outputs.push_docker_image == 'true' }}
          # Assign tags based on branch or tag type for clarity
          tags: |
            ${{ github.ref_type == 'branch' && github.ref_name == 'development' && matrix.name == 'main'
                && format('{0}:development', env.registry_and_name) || '' }}
            ${{ github.ref_type == 'branch' && github.ref_name == 'development' && matrix.name == 'classic'
                && format('{0}:development-classic', env.registry_and_name) || '' }}
            ${{ github.ref_type == 'branch' && github.ref_name == 'master' && matrix.name == 'main'
                && format('{0}:rolling', env.registry_and_name) || '' }}
            ${{ github.ref_type == 'branch' && github.ref_name == 'master' && matrix.name == 'classic'
                && format('{0}:rolling-classic', env.registry_and_name) || '' }}
            ${{ github.ref_type == 'tag' && matrix.name == 'main'
                && format('{0}:{1}', env.registry_and_name, github.ref_name) || '' }}
            ${{ github.ref_type == 'tag' && matrix.name == 'classic'
                && format('{0}:{1}-classic', env.registry_and_name, github.ref_name) || '' }}
            ${{ github.ref_type == 'tag' && matrix.name == 'main'
                && format('{0}:latest', env.registry_and_name) || '' }}
            ${{ github.ref_type == 'tag' && matrix.name == 'classic'
                && format('{0}:classic', env.registry_and_name) || '' }}
          build-args: |
            ${{ matrix.build_args }}
